### ISSUE TITLE
Preview of feeds does not work

### ISSUE THREAD

**Issue by jamietanna** [swentel/indigenous-android#340]
**Describe the bug**

Attempting to add a feed, and clicking `Preview` fails.

**To Reproduce**

1. Attempt to add a new feed
2. Click `Preview`

**Expected behavior**

Feed is previewed.

**Screenshots**

N/A

**Smartphone (please complete the following information):**

 - Device: Pixel 3A
 - Android version: 10

**Additional context**

My MicroSub reader is https://aperture.p3k.io/

I've been seeing this issue since the feature was first implemented, but I haven't raised it until now - sorry!

**Comment by swentel** [comment]
This is related with https://github.com/indieweb/microsub/issues/34

The spec says to use POST, but Aperture only accepts it on GET :)

I know Drupal Microsub and Yarns accept both GET and POST. I found it logical initially to use GET, but, as Aaron also suggests in that issue, POST is just safer to use.

So I think this should be fixed in Aperture and drupal and yarns should remove the existing GET.
