### ISSUE TITLE
"Click on Author" does not work (with Aperture?)

### ISSUE THREAD

**Issue by jamietanna** [swentel/indigenous-android#341]
**Describe the bug**

When clicking on an author, the feed does not change.

I am assuming similar to #339 and #340 it's due to an Aperture implementation issue?

**To Reproduce**

1. Enable the setting for Click on Author
2. Click Author

**Expected behavior**

Only author's posts are displayed.

**Screenshots**

N/A

**Smartphone (please complete the following information):**

 - Device: Pixel 3A
 - Android version: 10

**Additional context**

My MicroSub reader is https://aperture.p3k.io/

**Comment by swentel** [comment]
That might not necessarily be a bug in Aperture. It depends a bit on the case.

I think that Aperture supports viewing an individual feed, e.g. a dedicated feed when you follow an RSS feed, or microformats timeline. The Drupal microsub server supports that too.

However, there is the case when for instance using Granary and following a twitter feed. In that case, the author is the feed, so it becomes confusing. I should somehow trigger a search then on the author name in that channel, and I think Aperture also supports searching, but I should double check that.

So this might be a glitch indeed.

**Comment by bekopharm** [comment]
Same with Yarn btw. Affects any stream not just Granary ones. This is probably a limitation of the endpoint tho.

**Comment by swentel** [comment]
Looking at https://github.com/aaronpk/Aperture/blob/master/aperture/app/Http/Controllers/MicrosubController.php#L369 it seems that aperture should support it, so I think for Aperture the case of Granary doesn't work (can't test it myself as I use the Drupal server, but the Drupal server has the same problem). This could be solved by triggering a search, just need to decide what the logic should be.

As for yarns, looking at https://plugins.trac.wordpress.org/browser/yarns-microsub-server/trunk/includes/class-yarns-microsub-channels.php#L450 it doesn't seem that it supports this feature, so that should be feature request against that project.

**Comment by jamietanna** [comment]
Apologies, I've just retested and I can confirm that:

- Aperture works when on my i.e. blogroll, with well formed MF2 authors from an h-feed
- Aperture does not work when using Granary
- Aperture does not work when using i.e. https://news.indieweb.org/en/

**Comment by swentel** [comment]
Yep, confirms my thoughts, a timeline which contains aggregated feeds needs to act differently 

- e.g. trigger a search, I would suggest 'author name'
- we need to decide on microsub level how we can indicate that an item comes from an aggregated feed, that's the tricky part.

**Comment by swentel** [comment]
Commited something that will trigger a search for Twitter, looking at the url for the entry. Works great with the Drupal microsub server.

It's not perfect and hardcoded, so we really need a more robust way. https://github.com/indieweb/microsub/issues/21 is for that.

**Comment by swentel** [comment]
Closing this in favor to fix this on the server level.
