### ISSUE TITLE
error message for auth failure disappears too quickly

### ISSUE THREAD

**Issue by smaffulli** [swentel/indigenous-android#363]
Setting up the app for the first time, I enter the URL of my domain https://maffulli.net. I see a popup at the bottom saying something about domain missing `necessary rel links on your domain`.
IndieAuth on maffulli.net works fine on https://indieauth.com/

this is happening on a LG device, Android version 9. Any suggestions?

**Comment by smaffulli** [comment]
OK, after trying again and again and again, I managed to get authenticated. That's a weird error message. The app is looking for a reader endpoint, which I guess I have not configured yet on my domain. All good... except maybe a suggestion to improve the error handling?

**Comment by swentel** [comment]
Hmm you're right, I should start adding a 'Dismiss' button for error messages. I'll reopen to fix that.

As for the rel links it searches: it needs an authorization and token endpoint + either micropub or microsub.

I guess it's possible that due to caching, either on site/server level, or OS level, changes in your html or header are not found directly.

However, glad that it worked out in the end.

But as you suggest, I'll open this for better documentation and error handling! :)

**Comment by swentel** [comment]
Improved the error handling: they don't hide by default anymore (in all places, e.g. also micropub error messages etc). Also added information which endpoints need to be available on the domain.
