### ISSUE TITLE
Can not post to WordPress

### ISSUE THREAD

**Issue by jgmac1106** [swentel/indigenous-android#71]
I am able to sign using IndieAuth but when I go to post a note, reply, or article I get:  "Note post failed. Status code 401; message; "Unauthorized"

**Comment by swentel** [comment]
do you have the latest version of the app ? I know there was a problem with the access token for wordpres which was fixed in https://github.com/swentel/indigenous-android/commit/af11c8f5a73219957c0b01217d3e258eced1dd98 if you have the latest version, something else is at play, but no idea what to be honest.

**Comment by jgmac1106** [comment]
I am going to close this issue as it is not specific to indigenous but with a problem with my endpoints in general
