### ISSUE TITLE
Custom post types

### ISSUE THREAD

**Issue by dshanske** [swentel/indigenous-android#91]
Crazy thought. What if there was a way to define a custom post type? Add properties and save? Then you wouldn't have to code new post types, anyone could build them inside the app?

**Comment by swentel** [comment]
Not a crazy thought, I have been thinking about this already :)

I already have a powerful base class which allows me create new post types in about 5 minutes, making this dynamic should be quite easy I think.

**Comment by dshanske** [comment]
I would love this if you could. Along with an import/export function for sharing someday afterward.

**Comment by Ruxton** [comment]
This works where you can say "post is just a note with a different type" but it gets crazy once you start suggesting a user could define a new type to handle anything with a custom property.

**Comment by swentel** [comment]
I've given this a very long thought, and I'm not going to do this.

While it's very tempting, and in a way kind of logical since I can make many custom types via the UI on the Drupal side, it's going to be tricky to get this right in the app, let alone have a nice icon for instance too :)

Adding a new post type really just takes me around 10 minutes, and with post-type-discovery partially in (see #111 ), the list of options on the micropub screen can be limited in the future anyway.
