### ISSUE TITLE
Syndicating with Bridgy to Twitter 

### ISSUE THREAD

**Issue by jgmac1106** [swentel/indigenous-android#93]
The reply post type when syndicating to Twitter doesn't get shared as a reply to the tweet.

**Comment by swentel** [comment]
I've tested this with https://realize.be/reply/content/1524 which became a reply on https://twitter.com/mattiasgeniar/status/1035599981015650304 so it works for me at least when using the Drupal plugin.

The twitter url was in the reply link, and toggled syndication to twitter as well.

**Comment by EdwardHinkle** [comment]
@jgmac1106 The proper way for this is actually to just have the Micropub server automatically syndicate posts to Twitter. For example, my website pings brid.gy on every reply post. Brid.gy then will check the post I am replying to in order to see if 1) it's a twitter url or 2) if the url has an mf2 u-syndication link to a twitter url.

If it finds either of those, it will automatically syndicate the post to twitter
